### ISSUE TITLE
Celery build

### ISSUE THREAD

**Issue by ihd2911** [nayanchandni/docker-django-celery-rabbitmq#2]
Why we have to write the following code?

```
  worker:
    build:
      context: .
      dockerfile: Dockerfile
```

we already built it in web.
